server:
  port: 4002

redis:
  cache:
    expiration: 3600

spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(YXXxUQzO2qaxX2bJzDNKZg==)
    password: ENC(iIR6UImHnGfe4GOkWBFxtw==)
    url: ENC(2iQwaj+zoPqsm5Y+Y+upbh4GbG0yKOvIaGdMrEeqfqFFV5DxeBQDB7skNf/FK0LLEq78J96QfJeK9wJGVI9/a/D6huI3pKuS/Hy18yAxFsLbQj6Cy5FPZsXS3AuGXUL7u8IPl7bBOEpDpDl7gvlCbY6I2q83piJvdp90xQL9g4A=)
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: ENC(U86eYRZZD97vmgeakA91mgEnjyDcf//8)
    port: 5672
    username: ENC(e7wHwRdme5270KAOt4vRakfj/xn3Km5E)
    password: ENC(Lzx8NVEstZlX88Y/780BwVJ9TkFP3gFe)
  zipkin:
    rabbitmq:
      queue: ENC(HyNQN/6eBtFrhxeIujZ2gQ==)
  sleuth:
    sampler:
      percentage: 1.0

logging:
  config: classpath:logback.xml
