server:
  port: 1003

spring:
  rabbitmq:
    host: ENC(U86eYRZZD97vmgeakA91mgEnjyDcf//8)
    port: 5672
    username: ENC(e7wHwRdme5270KAOt4vRakfj/xn3Km5E)
    password: ENC(Lzx8NVEstZlX88Y/780BwVJ9TkFP3gFe)
  zipkin:
    rabbitmq:
      queue: ENC(HyNQN/6eBtFrhxeIujZ2gQ==)
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: system-auth-server,business-admin-server,business-pay-server,project-ditu-server,business-wechat-server
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    system-auth-server:
      path: /auth/**
      serviceId: system-auth-server
      stripPrefix: true
      sensitiveHeaders:
    business-admin-server:
      path: /admin/**
      serviceId: business-admin-server
      stripPrefix: true
      sensitiveHeaders:
    business-pay-server:
      path: /pay/**
      serviceId: business-pay-server
      stripPrefix: true
      sensitiveHeaders:
    business-wechat-server:
      path: /wechat/**
      serviceId: business-wechat-server
      stripPrefix: false
      sensitiveHeaders:
    project-ditu-server:
      path: /ditu/**
      serviceId: project-ditu-server
      stripPrefix: false
      sensitiveHeaders:
  ratelimit:
    key-prefix: business-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      business-admin-server:
        limit: 100
        quota: 100
        refresh-interval: 3

security:
  validate:
    code: false
  sessions: stateless
  oauth2:
    client:
      client-id: ENC(eZLNwFxeSKENBh1pu/M/rMMB76nxo/RLhWSaSLHa8+0=)
      client-secret: ENC(sKbpJGHz9JZmdydv1WOyAYjyXm2irxc0xYqvQ6VpF31uEw/FVNxYeA==)
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: system-gateway-server
      jwt:
         key-value: ENC(IgYggZdZPj8CkZOzE2mbzN5iWamRIP/uhB6Rh0WTK/AQkKRkXVGRQA+YYkcGvmX/)

urls:
  collects:
    - /mobile/**
    - /auth/**
    - /ditu/icemap/**
    - /ditu/pay/**
    - /ditu/css/**
    - /ditu/images/**
    - /ditu/js/**
    - /admin/code/*
    - /admin/api/info
    - /admin/api/userTree
    - /admin/api/dictType/*
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**

logging:
  config: classpath:logback.xml
